### ISSUE TITLE
Index re-open failure

### ISSUE THREAD

**Issue by missinglink** [pelias/elasticsearch-plugin#4]
Somewhere between [d1214b109c8395730c64ae552b2684b0847e44c5...92af4c640b21d33cfe407c8a9d9d3c0d501da12f](https://github.com/pelias/elasticsearch-plugin/compare/d1214b109c8395730c64ae552b2684b0847e44c5...92af4c640b21d33cfe407c8a9d9d3c0d501da12f) there was a regression which prevents indices from re-opening.

More information can be found on this ticket: https://github.com/pelias/geonames/issues/11

```bash
[2014-10-29 16:58:09,713][WARN ][indices.cluster          ] [Challenger] [pelias][2] failed to start shard
org.elasticsearch.index.gateway.IndexShardGatewayRecoveryException: [pelias][2] failed to recover shard
    at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:269)
    at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:132)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.engine.IndexFailedEngineException: [pelias][2] Index failed for [geoname#30477]
    at org.elasticsearch.index.engine.internal.InternalEngine.index(InternalEngine.java:499)
    at org.elasticsearch.index.shard.service.InternalIndexShard.performRecoveryOperation(InternalIndexShard.java:769)
    at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:250)
    ... 4 more
Caused by: java.lang.IllegalStateException: TokenStream contract violation: reset()/close() call missing, reset() called multiple times, or subclass does not call super.reset(). Please see Javadocs of TokenStream class for more information about the correct consuming workflow.
    at org.apache.lucene.analysis.Tokenizer$1.read(Tokenizer.java:111)
    at org.apache.lucene.analysis.util.CharacterUtils.readFully(CharacterUtils.java:230)
    at org.apache.lucene.analysis.util.CharacterUtils$Java5CharacterUtils.fill(CharacterUtils.java:272)
    at org.apache.lucene.analysis.util.CharacterUtils.fill(CharacterUtils.java:220)
    at org.apache.lucene.analysis.util.CharTokenizer.incrementToken(CharTokenizer.java:137)
    at org.apache.lucene.analysis.core.LowerCaseFilter.incrementToken(LowerCaseFilter.java:54)
    at org.apache.lucene.analysis.miscellaneous.ASCIIFoldingFilter.incrementToken(ASCIIFoldingFilter.java:104)
    at org.apache.lucene.analysis.pattern.PatternReplaceFilter.incrementToken(PatternReplaceFilter.java:69)
    at org.apache.lucene.analysis.synonym.SynonymFilter.parse(SynonymFilter.java:358)
    at org.apache.lucene.analysis.synonym.SynonymFilter.incrementToken(SynonymFilter.java:624)
    at org.apache.lucene.analysis.miscellaneous.WordDelimiterFilter.incrementToken(WordDelimiterFilter.java:237)
    at org.apache.lucene.analysis.PrefixAnalyzer$PrefixTokenFilter.incrementToken(PrefixAnalyzer.java:109)
    at org.apache.lucene.analysis.PrefixAnalyzer$PrefixTokenFilter.incrementToken(PrefixAnalyzer.java:109)
    at org.apache.lucene.analysis.TokenStreamToAutomaton.toAutomaton(TokenStreamToAutomaton.java:122)
    at org.apache.lucene.search.suggest.analyzing.XAnalyzingSuggester.toFiniteStrings(XAnalyzingSuggester.java:901)
    at org.elasticsearch.search.suggest.completion.AnalyzingCompletionLookupProvider.toFiniteStrings(AnalyzingCompletionLookupProvider.java:371)
    at org.elasticsearch.search.suggest.completion.CompletionTokenStream.incrementToken(CompletionTokenStream.java:63)
    at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:604)
    at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:342)
    at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:301)
    at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:241)
    at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:451)
    at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1539)
    at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1254)
    at org.elasticsearch.index.engine.internal.InternalEngine.innerIndex(InternalEngine.java:563)
    at org.elasticsearch.index.engine.internal.InternalEngine.index(InternalEngine.java:492)
    ... 6 more
[2014-10-29 16:58:09,720][WARN ][cluster.action.shard     ] [Challenger] [pelias][3] sending failed shard for [pelias][3], node[gsDJsFt2QO--0cgAju9XHA], [P], s[INITIALIZING], indexUUID [wvGLN_xWSc6kIHqjXetG6A], reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[pelias][3] failed to recover shard]; nested: IndexFailedEngineException[[pelias][3] Index failed for [geoname#30470]]; nested: IllegalStateException[TokenStream contract violation: reset()/close() call missing, reset() called multiple times, or subclass does not call super.reset(). Please see Javadocs of TokenStream class for more information about the correct consuming workflow.]; ]]
```

**Comment by missinglink** [comment]
this issue has not been reported again in the past 8 months so I'm marking it as resolved
